name: Xamarin mac, Android, iOS

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Setup nodejs
      uses: actions/setup-node@v1
    - name: Restore packages
      run: nuget restore
    - name: Yarn
      working-directory: ./src/BlazorWebView.JS/upstream/aspnetcore/web.js
      run: yarn
    - name: Build BlazorWebView.JS
      working-directory: ./src/BlazorWebView.JS/
      run: dotnet build --configuration Release
    - name: Build BlazorWebView
      working-directory: ./src/BlazorWebView/
      run: dotnet build --configuration Release
    - name: Build BlazorWebView.Android
      working-directory: ./src/BlazorWebView.Android/
      run: |
        dotnet restore
        msbuild BlazorWebView.Android.csproj /t:Build /p:Configuration=Release
    - name: Build BlazorWebView.Mac
      working-directory: ./src/BlazorWebView.Mac/
      run: |
        dotnet restore
        msbuild BlazorWebView.Mac.csproj /t:Build /p:Configuration=Release
    - name: Build BlazorWebView.iOS
      working-directory: ./src/BlazorWebView.iOS/
      run: |
        dotnet restore
        msbuild BlazorWebView.iOS.csproj /t:Build /p:Configuration=Release
    - name: Push BlazorWebView.Android nuget package
      working-directory: ./src/BlazorWebView.Android/
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - name: Push BlazorWebView.Mac nuget package
      working-directory: ./src/BlazorWebView.Mac/
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
    - name: Push BlazorWebView.iOS nuget package
      working-directory: ./src/BlazorWebView.iOS/
      run: dotnet nuget push **/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
